# Generated by Django 2.2 on 2021-04-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
