# Generated by Django 2.2 on 2021-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210422_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionary',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfunctionary',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
