# Generated by Django 2.2 on 2021-04-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_historicalroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='functionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.Functionary'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.Room'),
        ),
    ]
