# Generated by Django 2.2 on 2021-11-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210517_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='functionarys',
            field=models.ManyToManyField(related_name='spacefunctionarys', to='api.Functionary'),
        ),
    ]
