# Generated by Django 2.2 on 2021-11-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_folder_historicalfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='guide_file',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='guide_file',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
