# Generated by Django 2.2 on 2022-03-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211117_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
