# Generated by Django 2.2 on 2022-03-04 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20220301_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvidence',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('re_expiration_date', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('evidence_link', models.CharField(max_length=255, null=True)),
                ('evidence_file', models.TextField(blank=True, db_column='file_url', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('folder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Folder')),
                ('functionary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Functionary')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical evidence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('re_expiration_date', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('evidence_link', models.CharField(max_length=255, null=True)),
                ('evidence_file', models.FileField(blank=True, db_column='file_url', null=True, upload_to='EvidenceFile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folderevidence', to='api.Folder')),
                ('functionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functionaryevidence', to='api.Functionary')),
            ],
            options={
                'verbose_name': 'evidence',
                'verbose_name_plural': 'evidences',
                'ordering': ['-id'],
            },
        ),
    ]
